spring:
  application:
    name: dp01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_first
    username: root
    password: Wuhan123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

